scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'cadvisor'
    scrape_interval: 5s 
    static_configs:
      - targets: ['cadvisor:8080']
      
  - job_name: 'node'
    static_configs:
      - targets: ['172.17.0.1:9100']

